In [12]:
'''splines as feature'''
%run functions.py
%matplotlib notebook
# %run dataset.py

In [97]:
%run dataset.py

IndexError: list index out of range

In [98]:
print(i)
partic = returnDetails(tracings[0])['partID']
partic
tracings[i]

588

'14Oct.i'

In [83]:
participants = pd.read_table('/home/tejaswik/Documents/CurrentProjects/melmot/participants.csv',sep=';')
participants

    ID sex  age  scoreMus
0    1   F   26       175
1    2   M   23       465
2    3   F   53       989
3    4   F   29       972
4    5   M   26       958
5    6   M   30       563
6    7   M   37       973
7    8   M   25       839
8    9   F   20       262
9   10   F   31       913
10  11   F   24       438
11  12   M   25       702
12  13   F   27       100
13  14   F   31       995
14  15   M   28       829
15  16   F   31       912
16  17   M   35       950
17  18   F   31       325
18  19   M   30       992
19  20   M   34       467
20  21   F   20       499
21  22   F   49       965
22  23   F   28       524
23  24   M   33       213
24  25   M   24       865
25  26   M   64       879
26  27   M   34       924
27  28   F   29       992
28  29   F   41       662
29  30   M   33       986
30  31   F   23       566
31  32   F   24       319